(defproblem problem domain 
  (
    (associated_Contact contact1 headOfDepartment)
    (associated_Contact contact2 peer1)
    (associated_Contact contact3 peer2)
    (associated_Contact contact4 peer3)
    (associated_Contact contact5 peer4)
    (associated_Picture contact1 headOfDepartmentPicture)
    (associated_Picture contact2 peer1Picture)
    (created contact1)
    (created contact2)
    (created contact3)
    (created contact4)
    (created contact5)
    (haveInformation_Contactable headOfDepartment headOfDepartmentEMailAddress)
    (haveInformation_Contactable peer1 peer1EMailAddress)
    (haveInformation_Contactable peer2 peer2EMailAddress)
    (haveInformation_Contactable peer3 peer3EMailAddress)
    (haveInformation_Contactable peer4 peer4EMailAddress)
    (haveInformation_Regular agenda)
    (haveInformation_Regular dateForMeeting)
    (haveInformation_Regular headOfDepartmentPicture)
    (haveInformation_Regular peer1Picture)
    (haveInformation_Regular room101)
    (inMode_Home)
    (inUse contact1)
    (inUse contact2)
    (inUse contact3)
    (inUse contact4)
    (inUse contact5)
    (isFavourite contact1)
    (isFavourite contact2)
    (selected account1)
    (type_Agenda agenda)
    (type_Appointment appointmentForMeeting)
    (type_Contact contact1)
    (type_Contact contact2)
    (type_Contact contact3)
    (type_Contact contact4)
    (type_Contact contact5)
    (type_Contactable headOfDepartment)
    (type_Contactable peer1)
    (type_Contactable peer2)
    (type_Contactable peer3)
    (type_Contactable peer4)
    (type_ContactableInformation headOfDepartmentEMailAddress)
    (type_ContactableInformation peer1EMailAddress)
    (type_ContactableInformation peer2EMailAddress)
    (type_ContactableInformation peer3EMailAddress)
    (type_ContactableInformation peer4EMailAddress)
    (type_Creatable appointmentForMeeting)
    (type_Creatable contact1)
    (type_Creatable contact2)
    (type_Creatable contact3)
    (type_Creatable contact4)
    (type_Creatable contact5)
    (type_Creatable taskCreateHandout)
    (type_Date dateForMeeting)
    (type_EMail email1)
    (type_EMail email2)
    (type_EMail email3)
    (type_EMail email4)
    (type_EMail email5)
    (type_EMailAccount account1)
    (type_EMailAddress headOfDepartmentEMailAddress)
    (type_EMailAddress peer1EMailAddress)
    (type_EMailAddress peer2EMailAddress)
    (type_EMailAddress peer3EMailAddress)
    (type_EMailAddress peer4EMailAddress)
    (type_Information agenda)
    (type_Information dateForMeeting)
    (type_Information headOfDepartmentEMailAddress)
    (type_Information headOfDepartmentPicture)
    (type_Information peer1EMailAddress)
    (type_Information peer1Picture)
    (type_Information peer2EMailAddress)
    (type_Information peer3EMailAddress)
    (type_Information peer4EMailAddress)
    (type_Information room101)
    (type_Location room101)
    (type_Message email1)
    (type_Message email2)
    (type_Message email3)
    (type_Message email4)
    (type_Message email5)
    (type_Person headOfDepartment)
    (type_Person peer1)
    (type_Person peer2)
    (type_Person peer3)
    (type_Person peer4)
    (type_Picture headOfDepartmentPicture)
    (type_Picture peer1Picture)
    (type_RegularInformation agenda)
    (type_RegularInformation dateForMeeting)
    (type_RegularInformation headOfDepartmentPicture)
    (type_RegularInformation peer1Picture)
    (type_RegularInformation room101)
    (type_Selectable account1)
    (type_Selectable appointmentForMeeting)
    (type_Selectable contact1)
    (type_Selectable contact2)
    (type_Selectable contact3)
    (type_Selectable contact4)
    (type_Selectable contact5)
    (type_Selectable taskCreateHandout)
    (type_Task taskCreateHandout)
    (type_TransferableByCall dateForMeeting)
    (type_TransferableByCall headOfDepartmentEMailAddress)
    (type_TransferableByCall peer1EMailAddress)
    (type_TransferableByCall peer2EMailAddress)
    (type_TransferableByCall peer3EMailAddress)
    (type_TransferableByCall peer4EMailAddress)
    (type_TransferableByCall room101)
    (type_TransferableByEmail agenda)
    (type_TransferableByEmail dateForMeeting)
    (type_TransferableByEmail headOfDepartmentEMailAddress)
    (type_TransferableByEmail headOfDepartmentPicture)
    (type_TransferableByEmail peer1EMailAddress)
    (type_TransferableByEmail peer1Picture)
    (type_TransferableByEmail peer2EMailAddress)
    (type_TransferableByEmail peer3EMailAddress)
    (type_TransferableByEmail peer4EMailAddress)
    (type_TransferableByEmail room101)
    (type_TransferableByEmailContactable headOfDepartmentEMailAddress)
    (type_TransferableByEmailContactable peer1EMailAddress)
    (type_TransferableByEmailContactable peer2EMailAddress)
    (type_TransferableByEmailContactable peer3EMailAddress)
    (type_TransferableByEmailContactable peer4EMailAddress)
    (type_TransferableByEmailRegular agenda)
    (type_TransferableByEmailRegular dateForMeeting)
    (type_TransferableByEmailRegular headOfDepartmentPicture)
    (type_TransferableByEmailRegular peer1Picture)
    (type_TransferableByEmailRegular room101)
    (type_TransferableByPhoneContactable headOfDepartmentEMailAddress)
    (type_TransferableByPhoneContactable peer1EMailAddress)
    (type_TransferableByPhoneContactable peer2EMailAddress)
    (type_TransferableByPhoneContactable peer3EMailAddress)
    (type_TransferableByPhoneContactable peer4EMailAddress)
    (type_TransferableByPhoneRegular dateForMeeting)
    (type_TransferableByPhoneRegular room101)
    (type_TransferableBySMS dateForMeeting)
    (type_TransferableBySMS headOfDepartmentEMailAddress)
    (type_TransferableBySMS peer1EMailAddress)
    (type_TransferableBySMS peer2EMailAddress)
    (type_TransferableBySMS peer3EMailAddress)
    (type_TransferableBySMS peer4EMailAddress)
    (type_TransferableBySMS room101)
    (type_TransferableBySMSContactable headOfDepartmentEMailAddress)
    (type_TransferableBySMSContactable peer1EMailAddress)
    (type_TransferableBySMSContactable peer2EMailAddress)
    (type_TransferableBySMSContactable peer3EMailAddress)
    (type_TransferableBySMSContactable peer4EMailAddress)
    (type_TransferableBySMSRegular dateForMeeting)
    (type_TransferableBySMSRegular room101)
    (type_sort_for_account1 account1)
    (type_sort_for_agenda agenda)
    (type_sort_for_appointmentForMeeting appointmentForMeeting)
    (type_sort_for_contact1 contact1)
    (type_sort_for_contact2 contact2)
    (type_sort_for_contact3 contact3)
    (type_sort_for_contact4 contact4)
    (type_sort_for_contact5 contact5)
    (type_sort_for_dateForMeeting dateForMeeting)
    (type_sort_for_email1 email1)
    (type_sort_for_email2 email2)
    (type_sort_for_email3 email3)
    (type_sort_for_email4 email4)
    (type_sort_for_email5 email5)
    (type_sort_for_headOfDepartment headOfDepartment)
    (type_sort_for_headOfDepartmentEMailAddress headOfDepartmentEMailAddress)
    (type_sort_for_headOfDepartmentPicture headOfDepartmentPicture)
    (type_sort_for_peer1 peer1)
    (type_sort_for_peer1EMailAddress peer1EMailAddress)
    (type_sort_for_peer1Picture peer1Picture)
    (type_sort_for_peer2 peer2)
    (type_sort_for_peer2EMailAddress peer2EMailAddress)
    (type_sort_for_peer3 peer3)
    (type_sort_for_peer3EMailAddress peer3EMailAddress)
    (type_sort_for_peer4 peer4)
    (type_sort_for_peer4EMailAddress peer4EMailAddress)
    (type_sort_for_room101 room101)
    (type_sort_for_taskCreateHandout taskCreateHandout)
  )
  ((__top))
)
