(defproblem problem domain 
  (
    (haveInformation_Contactable dave davesEMailAddress)
    (haveInformation_Contactable greg gregsMobileNumber)
    (inMode_Home)
    (selected myEMailAccount)
    (haveInformation_Regular dateForMeeting)
    (haveInformation_Regular locationForMeeting)
    (type_Appointment appointmentForMeeting)
    (type_Call call1)
    (type_Contactable dave)
    (type_Contactable greg)
    (type_ContactableInformation davesEMailAddress)
    (type_ContactableInformation gregsMobileNumber)
    (type_Creatable appointmentForMeeting)
    (type_Date dateForMeeting)
    (type_EMail email1)
    (type_EMailAccount myEMailAccount)
    (type_EMailAddress davesEMailAddress)
    (type_Information dateForMeeting)
    (type_Information davesEMailAddress)
    (type_Information gregsMobileNumber)
    (type_Information locationForMeeting)
    (type_Location locationForMeeting)
    (type_Message call1)
    (type_Message email1)
    (type_NumberMobile gregsMobileNumber)
    (type_Person dave)
    (type_Person greg)
    (type_RegularInformation dateForMeeting)
    (type_RegularInformation locationForMeeting)
    (type_Selectable appointmentForMeeting)
    (type_Selectable myEMailAccount)
    (type_TransferableByCall dateForMeeting)
    (type_TransferableByCall davesEMailAddress)
    (type_TransferableByCall gregsMobileNumber)
    (type_TransferableByCall locationForMeeting)
    (type_TransferableByEmail dateForMeeting)
    (type_TransferableByEmail davesEMailAddress)
    (type_TransferableByEmail gregsMobileNumber)
    (type_TransferableByEmail locationForMeeting)
    (type_TransferableByEmailContactable davesEMailAddress)
    (type_TransferableByEmailContactable gregsMobileNumber)
    (type_TransferableByEmailRegular dateForMeeting)
    (type_TransferableByEmailRegular locationForMeeting)
    (type_TransferableByPhoneContactable davesEMailAddress)
    (type_TransferableByPhoneContactable gregsMobileNumber)
    (type_TransferableByPhoneRegular dateForMeeting)
    (type_TransferableByPhoneRegular locationForMeeting)
    (type_TransferableBySMS dateForMeeting)
    (type_TransferableBySMS davesEMailAddress)
    (type_TransferableBySMS gregsMobileNumber)
    (type_TransferableBySMS locationForMeeting)
    (type_TransferableBySMSContactable davesEMailAddress)
    (type_TransferableBySMSContactable gregsMobileNumber)
    (type_TransferableBySMSRegular dateForMeeting)
    (type_TransferableBySMSRegular locationForMeeting)
    (type_sort_for_appointmentForMeeting appointmentForMeeting)
    (type_sort_for_call1 call1)
    (type_sort_for_dateForMeeting dateForMeeting)
    (type_sort_for_dave dave)
    (type_sort_for_davesEMailAddress davesEMailAddress)
    (type_sort_for_email1 email1)
    (type_sort_for_greg greg)
    (type_sort_for_gregsMobileNumber gregsMobileNumber)
    (type_sort_for_locationForMeeting locationForMeeting)
    (type_sort_for_myEMailAccount myEMailAccount)
  )
  ((__top))
)
