(defproblem problem domain 
  (
    (associated_Contact contact1 headOfDepartment)
    (associated_Picture contact1 headOfDepartmentPicture)
    (created contact1)
    (haveInformation_Contactable headOfDepartment headOfDepartmentEMailAddress)
    (haveInformation_Regular agenda)
    (haveInformation_Regular dateForMeeting)
    (haveInformation_Regular headOfDepartmentPicture)
    (haveInformation_Regular room101)
    (inMode_Home)
    (inUse contact1)
    (isFavourite contact1)
    (selected account1)
    (type_Agenda agenda)
    (type_Contact contact1)
    (type_Contactable headOfDepartment)
    (type_ContactableInformation headOfDepartmentEMailAddress)
    (type_Creatable contact1)
    (type_Date dateForMeeting)
    (type_EMail email1)
    (type_EMailAccount account1)
    (type_EMailAddress headOfDepartmentEMailAddress)
    (type_Information agenda)
    (type_Information dateForMeeting)
    (type_Information headOfDepartmentEMailAddress)
    (type_Information headOfDepartmentPicture)
    (type_Information room101)
    (type_Location room101)
    (type_Message email1)
    (type_Person headOfDepartment)
    (type_Picture headOfDepartmentPicture)
    (type_RegularInformation agenda)
    (type_RegularInformation dateForMeeting)
    (type_RegularInformation headOfDepartmentPicture)
    (type_RegularInformation room101)
    (type_Selectable account1)
    (type_Selectable contact1)
    (type_TransferableByCall dateForMeeting)
    (type_TransferableByCall headOfDepartmentEMailAddress)
    (type_TransferableByCall room101)
    (type_TransferableByEmail agenda)
    (type_TransferableByEmail dateForMeeting)
    (type_TransferableByEmail headOfDepartmentEMailAddress)
    (type_TransferableByEmail headOfDepartmentPicture)
    (type_TransferableByEmail room101)
    (type_TransferableByEmailContactable headOfDepartmentEMailAddress)
    (type_TransferableByEmailRegular agenda)
    (type_TransferableByEmailRegular dateForMeeting)
    (type_TransferableByEmailRegular headOfDepartmentPicture)
    (type_TransferableByEmailRegular room101)
    (type_TransferableByPhoneContactable headOfDepartmentEMailAddress)
    (type_TransferableByPhoneRegular dateForMeeting)
    (type_TransferableByPhoneRegular room101)
    (type_TransferableBySMS dateForMeeting)
    (type_TransferableBySMS headOfDepartmentEMailAddress)
    (type_TransferableBySMS room101)
    (type_TransferableBySMSContactable headOfDepartmentEMailAddress)
    (type_TransferableBySMSRegular dateForMeeting)
    (type_TransferableBySMSRegular room101)
    (type_sort_for_account1 account1)
    (type_sort_for_agenda agenda)
    (type_sort_for_contact1 contact1)
    (type_sort_for_dateForMeeting dateForMeeting)
    (type_sort_for_email1 email1)
    (type_sort_for_headOfDepartment headOfDepartment)
    (type_sort_for_headOfDepartmentEMailAddress headOfDepartmentEMailAddress)
    (type_sort_for_headOfDepartmentPicture headOfDepartmentPicture)
    (type_sort_for_room101 room101)
  )
  ((__top))
)
