(defproblem problem domain 
  (
    (associated_Contact contact1 Biundo)
    (associated_Picture contact1 BiundoPicture)
    (created contact1)
    (haveInformation_Contactable Biundo BiundoEMailAddress)
    (haveInformation_Contactable Biundo BiundoOfficeNumber)
    (haveInformation_Regular agenda)
    (haveInformation_Regular dateForMeeting)
    (haveInformation_Regular BiundoPicture)
    (haveInformation_Regular room101)
    (inMode_Home)
    (inUse contact1)
    (isFavourite contact1)
    (selected account1)
    (type_Agenda agenda)
    (type_Call call1)
    (type_Contact contact1)
    (type_Contactable Biundo)
    (type_ContactableInformation BiundoEMailAddress)
    (type_ContactableInformation BiundoOfficeNumber)
    (type_Creatable contact1)
    (type_Date dateForMeeting)
    (type_EMail email1)
    (type_EMailAccount account1)
    (type_EMailAddress BiundoEMailAddress)
    (type_Information BiundoEMailAddress)
    (type_Information BiundoOfficeNumber)
    (type_Information BiundoPicture)
    (type_Information agenda)
    (type_Information dateForMeeting)
    (type_Information room101)
    (type_Location room101)
    (type_Message call1)
    (type_Message email1)
    (type_Message sms1)
    (type_NumberOffice BiundoOfficeNumber)
    (type_Person Biundo)
    (type_Picture BiundoPicture)
    (type_RegularInformation BiundoPicture)
    (type_RegularInformation agenda)
    (type_RegularInformation dateForMeeting)
    (type_RegularInformation room101)
    (type_SMS sms1)
    (type_Selectable account1)
    (type_Selectable contact1)
    (type_TransferableByCall BiundoEMailAddress)
    (type_TransferableByCall BiundoOfficeNumber)
    (type_TransferableByCall dateForMeeting)
    (type_TransferableByCall room101)
    (type_TransferableByEmail BiundoEMailAddress)
    (type_TransferableByEmail BiundoOfficeNumber)
    (type_TransferableByEmail BiundoPicture)
    (type_TransferableByEmail agenda)
    (type_TransferableByEmail dateForMeeting)
    (type_TransferableByEmail room101)
    (type_TransferableByEmailContactable BiundoEMailAddress)
    (type_TransferableByEmailContactable BiundoOfficeNumber)
    (type_TransferableByEmailRegular BiundoPicture)
    (type_TransferableByEmailRegular agenda)
    (type_TransferableByEmailRegular dateForMeeting)
    (type_TransferableByEmailRegular room101)
    (type_TransferableByPhoneContactable BiundoEMailAddress)
    (type_TransferableByPhoneContactable BiundoOfficeNumber)
    (type_TransferableByPhoneRegular dateForMeeting)
    (type_TransferableByPhoneRegular room101)
    (type_TransferableBySMS BiundoEMailAddress)
    (type_TransferableBySMS BiundoOfficeNumber)
    (type_TransferableBySMS dateForMeeting)
    (type_TransferableBySMS room101)
    (type_TransferableBySMSContactable BiundoEMailAddress)
    (type_TransferableBySMSContactable BiundoOfficeNumber)
    (type_TransferableBySMSRegular dateForMeeting)
    (type_TransferableBySMSRegular room101)
    (type_sort_for_Biundo Biundo)
    (type_sort_for_BiundoEMailAddress BiundoEMailAddress)
    (type_sort_for_BiundoOfficeNumber BiundoOfficeNumber)
    (type_sort_for_BiundoPicture BiundoPicture)
    (type_sort_for_account1 account1)
    (type_sort_for_agenda agenda)
    (type_sort_for_contact1 contact1)
    (type_sort_for_dateForMeeting dateForMeeting)
    (type_sort_for_room101 room101)
  )
  ((__top))
)
